export const USER_LOADING = "USER_LOADING";

export const USER_LOADED = "USER_LOADED";
export const USER_AUTH_ERR = "USER_AUTH_ERR";

export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const GET_MESSAGE = "GET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";

export const FORGETPASSWORD_SUCCESSFUL = "FORGET_PASSWORD_SUCCESSFUL";
export const FORGETPASSWORD_ERR = "FORGET_PAASSWORD_ERR";

export const RESETPASSWORD_SUCCESSFUL = "RESET_PASSWORD_SUCCESSFUL";
export const RESETPASSWORD_ERR = "RESET_PASSWORD_ERR";

// blog types
export const POST = "POST-BLOG";
export const POST_ERROR = "POST-ERROR";
export const FETCH = "FETCH-BLOG";
export const USER_FETCH = "USER-FETCH";
export const PATCH = "PATCH-BLOG";
export const DELETE = "DELETE-BLOG";
export const BLOG_LIKE = "LIKE-UPDATE";
